### ISSUE TITLE
Thumbnail sizes are wrong in paginator

### ISSUE THREAD

**Issue by demiankatz** [FalveyLibraryTechnology/VuDL#198]
The sizing of thumbnails is not quite right in the paginator -- most thumbnails are being enlarged beyond their actual size, causing blurriness. More seriously, images with unusual aspect ratios (e.g. a tall, thin spine image) are not being properly constrained. See screen shot:

![image](https://user-images.githubusercontent.com/309069/208482262-0d1ea2a2-92e0-43bd-8491-df64e2188b69.png)

**Comment by crhallberg** [comment]
8c2ff14a5df1acddf727b797585a0390765269e5
