### ISSUE TITLE
"Can't open tesseract.config" during ingest

### ISSUE THREAD

**Issue by demiankatz** [FalveyLibraryTechnology/VuDL#240]
During the ingest process, I regularly see messages like:

`read_params_file: Can't open /opt/vudl-data/holdingarea/Pennsylvania/Jan046P//ocr/tesseract.config`

However, OCR is generating correctly.

**Comment by Geoffsc** [comment]
this may be an issue with the tesseract command in ImageFile.ocr() line 93:
`this.config.tesseractPath + " " + deriv + " " + txt.slice(0, -4) + " " + this.ocrProperties();`

unfortunately I no longer have a test environment but I'd maybe check what the command is and try it from the command line from the same folder manually and see if you get the same issue?

**Comment by demiankatz** [comment]
Thanks, @Geoffsc, will do! I don't think this is a major problem, but I wanted to document it so I can investigate further when time permits -- I'm planning to clean up some of the biggest known UI problems first, and then circle back to some of these smaller backend hiccups. :-) In any case, I appreciate you keeping an eye on things!

**Comment by demiankatz** [comment]
I can no longer reproduce this issue; it's possible that it went away with the move from Tesseract v3 to v4.
